version: "3.0"
services:
  express:
    # specify the directory of the application containing of the Dockerfile
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"