version: "3.0"
services:
  express:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  db:
    image: mongo
    ports:
      - "27017:27017"